
script-setting:
  # 注释匹配规则
  comment-pattern:
    # 单行注释
    # 匹配 // 及其后所有字符直至换行
    single-line: '(?<!\\)//[^\n]*(?=\n)'
    # 多行注释
    # 匹配 /* 直到 */
    multi-line: '(?<!\\)/\*[^(\*/)]*\*/'

schedule-setting:
  # 指定默认情况下的日期格式
  # yyyy - 年份
  # MM - 月份
  # dd - 当月的天数
  # HH - 二十四小时制
  # hh - 十二小时制
  # mm - 分钟
  # ss - 秒
  date-format: 'yyyy-MM-dd HH:mm:ss'

# 调试等级
# off - 关闭
# normal - 普通
# high - 高
# highest - 最高
# monitor - 观察
debug: off